---
title: "Recursos para profesores"
description: |
  Recursos para clases en línea de Economía.
author:
  - name: Mario Alberto García MEza
    url: https://marionomics.com/recursos
date: 12-23-2020
output:
  distill::distill_article:
    self_contained: false
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

#### Texto

* **Libro**: [The Economy](https://www.core-econ.org/the-economy/) por The CORE Team. Es un libro online gratuito con todo lo relevante de la economía moderna. La versión en español está completa hasta el capítulo 16 hasta el momento, pero la versión en inglés está completa. También existen ya versiones en francés e italiano disponibles.

* **Libro**: [Doing Economics](https://www.core-econ.org/doing-economics/index.html) por The CORE Team. Es un libro online gratuito con aplicaciones prácticas para economistas. Los ejercicios vienen con tutoriales en texto y en video que se pueden seguir en Excel, R o Google Sheets. El libro está en inglés.

#### Video 

* **Canal de YouTube**: [3blue1brown](https://www.youtube.com/channel/UCYO_jab_esuFRV4b17AJtAw). Es un canal sobre matemáticas en formato visual. Recomiendo ampliamente para todos los economistas que sigan la lista de reproducción sobre la esencia del cálculo y de álgebra lineal. También podría ser de interés a quienes están en áreas de desarrollo económico y finanzas la serie de ecuaciones diferenciales.

* **Canal de YouTube**: [Market Power](https://www.youtube.com/channel/UC9a_V7YbGGmWphAzk8_4LFQ). Un canal de Economía muy divertido.

* **YouTube**: [Crash Course: Economics](https://www.youtube.com/playlist?list=PL8dPuuaLjXtPNZwz5_o_5uirJ8gQXnhEO) Es una serie dentro del canal Crash Course, de los hermanos Greene. Vienen temas importante de cursos básicos de economía.


#### Sitios web

* **Instagram**: Mi cuenta de instagram, [marionomics](https://www.instagram.com/marionomics/)

* **Juego**: [Chair The FED](https://www.sffed-education.org/chairthefed/) Es una simulación de decisiones de política monetaria.

* **Juegos**: [Economics Games](https://www.sffed-education.org/chairthefed/) Juegos online gratuitos para enseñar economía.

* **Videos**: [Khan Academy: Economía](https://es.khanacademy.org/economics-finance-domain) Contiene videos con cursos de Microeconomía, Mercados financieros y de capitales, espíritu emprendedor y macroeconomía.