---
title: "Como Calcular el tamaño de muestra en R"
description: |
  Un tutorial corto
author:
  - name: Mario Alberto García Meza
    url: https://marionomics.com/muestra
date: 12-23-2020
output:
  distill::distill_article:
    self_contained: false
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Bases 
La base de la estadística inferencial es, como su nombre lo indica, obtener inferencias de una _población_ a partir de una muestra. Normalmente es una cuestión de administración de recursos escasos lo que nos obliga a hacerlo de esta manera, por lo que una pregunta razonable en un experimento o en un estudio es _¿De qué tamaño es la muestra que se necesita?_.

Una muestra más grande genera resultados más precisos, pero esto naturalmente incrementa los costos de operación, que vienen por el tiempo, el trabajo y el dinero que se debe invertir a la recolección de la información. Por el otro lado, si un tamaño de muestra es demasiado pequeña, los resultados pierden confiabilidad.

Para calcular el tamaño de muestra, es necesario conocer cuatro cosas

1. El tamaño de la respuesta que quieres detectar
2. La varianza de la respuesta
3. Los niveles de significancia deseados
4. el poder deseado

El tamaño de la respuesta se suele definir como **delta**, y se refiere a la diferencia que hay entre el _tratamiento_ y el placebo. En un experimento, al realizar esta comparación, esperas que exista un efecto entre estas variables. Definamos entonces $\Delta = \mu_1 - \mu_2$ donde $\mu_i, \quad i = 1,2$ es la medición de la media de uno de los grupos.

Después de eso, es necesario tomar consideraciones sobre