---
title: "Acerca de mi"
description: |
  Algunos datos sobre mi
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

Mi nombre es Mario Alberto García Meza, soy profesor/investigador en la [Universidad Juárez del Estado de Durango](ujed.mx) y este es mi blog.

### Sobre mi
Desde pequeño siempre quise ser científico. Viví de niño en Vicente Guerrero, Durango. Mi papá es biólogo y siempre me enseñó a apreciar la naturaleza y la vida, sobre todo los insectos de los cuales tenía una gran colección en el trabajo que me encantaba admirar.

Estudié la carrera en Administración en la FECA-UJED en Durango y más tarde la maestría en la Escuela Superior de Economía del Instituto Politécnico Nacional, en la Ciudad de México. Al terminar la maestría tomé una de las decisiones más importantes hasta el momento: hacer un doctorado y convertirme en investigador.

Entré al Doctorado en Ciencias Económicas en 2014 con una beca del Conacyt y entré a diferentes proyectos que me llevaron de viaje por toda la república a estudiar las pequeñas y medianas empresas. Esto me cambiaría la vida por siempre.

En 2015 asistí a un congreso en la ciudad de San Petersburgo, en Rusia, donde presenté por primera vez mi trabajo en ecuaciones diferenciales. Ahí me invitaron a tomar una estancia en 2016, donde conocí a María, mi esposa.

María regresó conmigo y desde entonces vivimos en la ciudad de Durango, donde tenemos dos hermosos hijos.

### Sobre mi trabajo

Soy profesor-investigador en la Universidad Juárez del Estado de Durango. Doy clase en licenciatura, maestría y Doctorado, principalmente de Economía y de métodos cuantitativos. Mi línea de investigación es la teoría de juegos diferencial en ocasiones, métodos cuantitativos e inferencia causal en otras y pequeñas empresas otras tantas veces.

Me encanta la divulgación de la ciencia. Puedes ver mis publicaciones en esta página.