---
title: "Research"
site: distill::distill_website
---

## Publicaciones

- **Complementarity of goods and cooperation among firms in a dynamic duopoly**
Garcia-Meza M.A., Gurrola-Rios C. (2020) Complementarity of Goods and Cooperation Among Firms in a Dynamic Duopoly. In: Petrosyan L.A., Mazalov V.V., Zenkevich N.A. (eds) _Frontiers of Dynamic Games. Static & Dynamic Game Theory: Foundations & Applications._ Birkhäuser, Cham. [DOI](https://doi.org/10.1007/978-3-030-51941-4_11)

- **Innovación a nivel Individual en las MIPES de la Ciudad de México: habilidades y resultados**
Neme-Castillo, O., Garcia-Meza, M.A., Valderrama-Santibáñez, A.L., (2020) Investigación Administrativa (En proceso de publicación)

- **Importancia económica de las ciudades medias en México**
García Meza, M. A., Valderrama Santibáñez, A. L., & Neme Castillo, O. (2019). Importancia económica de las ciudades medias en México. Región Y Sociedad, 31, e1241. [DOI](https://doi.org/10.22198/rys2019/31/1241)

- **Efectos de la deuda pública subnacional en la inversión pública productiva en México (Effects of subnational public debt on public productive investment in Mexico)**
García Meza, M. A. (2019). Efectos de la deuda pública subnacional en la inversión pública productiva en México. Análisis Económico 34(87). [Link](http://www.analisiseconomico.azc.uam.mx/index.php/rae/article/view/477)

- **Determinantes de las habilidades de innovación en las mypes de la Zona Metropolitana del Valle de México**
Valderrama Santibáñez, A. L., Neme Castillo, O., & García Meza, M. A. (2019). Determinantes de las habilidades de innovación en las mypes de la Zona Metropolitana del Valle de México. Innovar, 29(74), 11-23. [link](https://doi.org/10.15446/innovar.v29n74.82060)

- **Evaluation of Portfolio Decision Improvements by Markov Modulated Diffusion Processes: A Shapley Value Approach**
Vallejo-Jimenez B., Garcia-Meza M.A. (2019) Evaluation of Portfolio Decision Improvements by Markov Modulated Diffusion Processes: A Shapley Value Approach. In: Petrosyan L., Mazalov V., Zenkevich N. (eds) Frontiers of Dynamic Games. Static & Dynamic Game Theory: Foundations & Applications. Birkhäuser, Cham. [doi](https://doi.org/10.1007/978-3-030-23699-1_15)

- **Stable Marketing Cooperation in a Differential Game for an Oligopoly**
Mario A. García-Meza & Ekaterina Viktorovna Gromova & José Daniel López-Barrientos, 2018. "Stable Marketing Cooperation in a Differential Game for an Oligopoly," International Game Theory Review (IGTR), World Scientific Publishing Co. Pte. Ltd., vol. 20(03), pages 1-18, September. [doi](https://doi.org/10.1142/S0219198917500281)

- **A Bayesian structural time series approach to forecast Mexico’s consumer index**
García-Meza, M. A., & Venegas-Martínez, F. (2018). A Bayesian structural time series approach to forecast Mexico’s consumer index. Journal of Applied Economic Sciences, 615-626. [link](https://www.ceeol.com/search/article-detail?id=718542)

- **A Differential Game on Military Intervention and competition between drug cartels**
García, M. A. & Venegas-Martínez, F. (2018). A Differential Game on Military Intervention and competition between drug cartels. International Journal of Pure and Applied Mathematics, 119(4), 603-616. DOI: 10.12732/ijpam.v119i4.3 [link](https://ijpam.eu/contents/2018-119-4/3/index.html)

- **A Differential Game of a Duopoly with Network Externalities**
García-Meza M.A., López-Barrientos J.D. (2016) A Differential Game of a Duopoly with Network Externalities. In: Petrosyan L., Mazalov V. (eds) Recent Advances in Game Theory and Applications. Static & Dynamic Game Theory: Foundations & Applications. Birkhäuser, Cham. [doi](https://doi.org/10.1007/978-3-319-43838-2_3)

- **El motivo precautorio en la demanda de saldos reales: un enfoque ortodoxo.**
Venegas-Martínez, Francisco and Avendaño-Vargas, Blanca Lilia and García-Meza, Mario Alberto (2016): El motivo precautorio en la demanda de saldos reales: un enfoque ortodoxo. eseconomía, Escuela Superior de Economía, Instituto Politécnico Nacional, vol. 12(46), pages 7-20, [link](https://ideas.repec.org/a/ipn/esecon/v12y2017i46p7-20.html)